# Generated by Django 5.1 on 2025-03-08 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password_hash', models.TextField()),
                ('hash_method', models.CharField(choices=[('md5', 'md5'), ('sha1', 'sha1'), ('bcrypt', 'bcrypt'), ('argon2', 'argon2')], max_length=10)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
